import './currencyData.mock';
import './reactIntl.mock';
import './stripesComponents.mock';
import './stripesConfig.mock';
import './stripesCore.mock';
import './stripesIcon.mock';
import './stripesSmartComponent.mock';
import './matchMedia.mock';
import './react-virtualized-auto-sizer.mock';
